hgicf-objs += ctrl.o
hgicf-objs += core.o
hgicf-objs += event.o
hgicf-objs += procfs.o
hgicf-objs += ../utils/fwdl.o
hgicf-objs += ../utils/utils.o
hgicf-objs += ../utils/fwctrl.o
hgicf-objs += ../utils/ota.o
hgicf-objs += ../utils/fwinfo.o
hgicf-objs += ../utils/iwpriv.o
hgicf-$(CONFIG_HGIC_SDIO) += ../utils/if_sdio.o
hgicf-$(CONFIG_HGIC_USB)  += ../utils/if_usb.o


obj-$(CONFIG_HGICF)     += hgicf.o
